//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_inStudent
    {
        public int id { get; set; }
        public Nullable<int> extra_Course_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<decimal> course_recipt1 { get; set; }
        public Nullable<decimal> course_recipt2 { get; set; }
        public string note { get; set; }
        public Nullable<decimal> grade { get; set; }
    
        public virtual extra_Course extra_Course { get; set; }
        public virtual course_student course_student { get; set; }
    }
}
