//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course_student()
        {
            this.Course_inStudent = new HashSet<Course_inStudent>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BOD { get; set; }
        public Nullable<int> affiliate_id { get; set; }
        public Nullable<long> national_id { get; set; }
        public Nullable<int> phone_num { get; set; }
        public string Email { get; set; }
    
        public virtual affiliated_entity affiliated_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_inStudent> Course_inStudent { get; set; }
    }
}
