//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_CCTTEntities : DbContext
    {
        public DB_CCTTEntities()
            : base("name=DB_CCTTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nationality> nationality { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<Year> Year { get; set; }
        public virtual DbSet<Semester> Semester { get; set; }
        public virtual DbSet<degree> degree { get; set; }
        public virtual DbSet<major> major { get; set; }
        public virtual DbSet<qualification> qualification { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
        public virtual DbSet<Faculty_member> Faculty_member { get; set; }
        public virtual DbSet<main_course> main_course { get; set; }
        public virtual DbSet<study_Group> study_Group { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<num_semster> num_semster { get; set; }
        public virtual DbSet<main_course_rel_semster> main_course_rel_semster { get; set; }
        public virtual DbSet<semster_student> semster_student { get; set; }
        public virtual DbSet<semster_student_main_cours> semster_student_main_cours { get; set; }
        public virtual DbSet<affiliated_entity> affiliated_entity { get; set; }
        public virtual DbSet<course_student> course_student { get; set; }
        public virtual DbSet<extra_Course> extra_Course { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual ObjectResult<StloadDataPage_Semester_Result> StloadDataPage_Semester()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Semester_Result>("StloadDataPage_Semester");
        }
    
        public virtual ObjectResult<StloadDataPage_Semester1_Result> StloadDataPage_Semester1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Semester1_Result>("StloadDataPage_Semester1");
        }
    
        public virtual ObjectResult<StloadDataPage_trainer_Result> StloadDataPage_trainer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_trainer_Result>("StloadDataPage_trainer");
        }
    
        public virtual ObjectResult<StloadDataPage_trainer1_Result> StloadDataPage_trainer1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_trainer1_Result>("StloadDataPage_trainer1");
        }
    
        public virtual ObjectResult<StloadDataPage_Semester2_Result> StloadDataPage_Semester2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Semester2_Result>("StloadDataPage_Semester2");
        }
    
        public virtual ObjectResult<StloadDataPage_Semester11_Result> StloadDataPage_Semester11()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Semester11_Result>("StloadDataPage_Semester11");
        }
    
        public virtual ObjectResult<StloadDataPage_Faculty_member_Result> StloadDataPage_Faculty_member()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Faculty_member_Result>("StloadDataPage_Faculty_member");
        }
    
        public virtual ObjectResult<StloadDataPage_Faculty_member1_Result> StloadDataPage_Faculty_member1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Faculty_member1_Result>("StloadDataPage_Faculty_member1");
        }
    
        public virtual ObjectResult<StloadDataPage_Faculty_member2_Result> StloadDataPage_Faculty_member2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Faculty_member2_Result>("StloadDataPage_Faculty_member2");
        }
    
        public virtual ObjectResult<StloadDataPage_Faculty_member3_Result> StloadDataPage_Faculty_member3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Faculty_member3_Result>("StloadDataPage_Faculty_member3");
        }
    
        public virtual ObjectResult<StloadDataPage_Semester12_Result> StloadDataPage_Semester12()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Semester12_Result>("StloadDataPage_Semester12");
        }
    
        public virtual ObjectResult<StloadDataPage_Faculty_member31_Result> StloadDataPage_Faculty_member31()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Faculty_member31_Result>("StloadDataPage_Faculty_member31");
        }
    
        public virtual ObjectResult<StloadDataPage_student1_Result> StloadDataPage_student1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_student1_Result>("StloadDataPage_student1");
        }
    
        public virtual ObjectResult<StloadDataPage_study_Group1_Result> StloadDataPage_study_Group1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_study_Group1_Result>("StloadDataPage_study_Group1");
        }
    
        public virtual ObjectResult<string> StloadDataPage_getsemster_by_dep(Nullable<int> dep_id)
        {
            var dep_idParameter = dep_id.HasValue ?
                new ObjectParameter("dep_id", dep_id) :
                new ObjectParameter("dep_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("StloadDataPage_getsemster_by_dep", dep_idParameter);
        }
    
        public virtual ObjectResult<main_course_rel_semster1_Result> main_course_rel_semster1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<main_course_rel_semster1_Result>("main_course_rel_semster1");
        }
    
        public virtual ObjectResult<get_main_cours_student_Result> get_main_cours_student(Nullable<int> std_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_main_cours_student_Result>("get_main_cours_student", std_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> get_main_cours_student_year(Nullable<int> std_id, Nullable<int> year_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("get_main_cours_student_year", std_idParameter, year_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> get_main_cours_student_year1(Nullable<int> std_id, Nullable<int> year_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("get_main_cours_student_year1", std_idParameter, year_idParameter);
        }
    
        public virtual int get_main_cours_student_year5(Nullable<int> std_id, Nullable<int> year_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_main_cours_student_year5", std_idParameter, year_idParameter);
        }
    
        public virtual ObjectResult<StloadDataPage_Semester13_Result> StloadDataPage_Semester13()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StloadDataPage_Semester13_Result>("StloadDataPage_Semester13");
        }
    
        public virtual int tbl_insert_semster_student_main_cours(Nullable<int> year_id, Nullable<int> student_id, Nullable<int> main_cours_id)
        {
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var student_idParameter = student_id.HasValue ?
                new ObjectParameter("student_id", student_id) :
                new ObjectParameter("student_id", typeof(int));
    
            var main_cours_idParameter = main_cours_id.HasValue ?
                new ObjectParameter("main_cours_id", main_cours_id) :
                new ObjectParameter("main_cours_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tbl_insert_semster_student_main_cours", year_idParameter, student_idParameter, main_cours_idParameter);
        }
    
        public virtual ObjectResult<get_main_cours_student_grade1_Result> get_main_cours_student_grade1(Nullable<int> year_id, Nullable<int> main_cours_id)
        {
            var year_idParameter = year_id.HasValue ?
                new ObjectParameter("year_id", year_id) :
                new ObjectParameter("year_id", typeof(int));
    
            var main_cours_idParameter = main_cours_id.HasValue ?
                new ObjectParameter("main_cours_id", main_cours_id) :
                new ObjectParameter("main_cours_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_main_cours_student_grade1_Result>("get_main_cours_student_grade1", year_idParameter, main_cours_idParameter);
        }
    }
}
