//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty_member
    {
        public long National_id { get; set; }
        public Nullable<int> qualification { get; set; }
        public string name { get; set; }
        public Nullable<int> degree { get; set; }
        public Nullable<System.DateTime> BOD { get; set; }
        public Nullable<int> phone_num { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> start_work_Date { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> nationality { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<System.DateTime> graduation_date { get; set; }
        public Nullable<int> Major { get; set; }
        public string passport_id { get; set; }
        public string personal_id { get; set; }
        public Nullable<int> martial_status { get; set; }
        public string picture { get; set; }
        public string CV { get; set; }
        public string certificate_place_of_origin { get; set; }
        public Nullable<int> department { get; set; }
    
        public virtual degree degree1 { get; set; }
        public virtual department department1 { get; set; }
        public virtual major major1 { get; set; }
        public virtual nationality nationality1 { get; set; }
        public virtual qualification qualification1 { get; set; }
    }
}
