//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class main_course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public main_course()
        {
            this.main_course1 = new HashSet<main_course>();
            this.main_course11 = new HashSet<main_course>();
            this.main_course_rel_semster = new HashSet<main_course_rel_semster>();
            this.semster_student_main_cours = new HashSet<semster_student_main_cours>();
        }
    
        public int id { get; set; }
        public string code_id { get; set; }
        public string course_name { get; set; }
        public Nullable<int> units { get; set; }
        public Nullable<int> hours { get; set; }
        public Nullable<int> reliability { get; set; }
        public Nullable<int> substitute_for { get; set; }
        public Nullable<int> type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<main_course> main_course1 { get; set; }
        public virtual main_course main_course2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<main_course> main_course11 { get; set; }
        public virtual main_course main_course3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<main_course_rel_semster> main_course_rel_semster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<semster_student_main_cours> semster_student_main_cours { get; set; }
    }
}
