//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class semster_student_main_cours
    {
        public int id { get; set; }
        public Nullable<int> semster_student_id { get; set; }
        public Nullable<int> main_cours_id { get; set; }
        public Nullable<int> final_only { get; set; }
        public Nullable<int> halfe_grade { get; set; }
        public Nullable<int> final_grade { get; set; }
        public Nullable<int> state_rate { get; set; }
    
        public virtual main_course main_course { get; set; }
        public virtual semster_student semster_student { get; set; }
    }
}
