//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.semster_student = new HashSet<semster_student>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> BOD { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> nationality { get; set; }
        public string place_of_birth { get; set; }
        public Nullable<long> national_num { get; set; }
        public Nullable<int> phone_num { get; set; }
        public Nullable<int> parent_phone_num { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string picture { get; set; }
        public string certificate_type { get; set; }
        public Nullable<double> certifcate_grade { get; set; }
        public string certificate_place_of_origin { get; set; }
        public string major { get; set; }
        public Nullable<int> year_of_joining { get; set; }
        public Nullable<int> semster_of_joining { get; set; }
        public Nullable<int> year_of_graduation { get; set; }
        public string learning_system { get; set; }
        public Nullable<int> file_id { get; set; }
        public string parent_name { get; set; }
        public Nullable<int> family_paper_id { get; set; }
        public Nullable<int> study_group { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> state_sem { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> idColge { get; set; }
        public byte[] image { get; set; }
        public string student_search { get; set; }
    
        public virtual nationality nationality1 { get; set; }
        public virtual Semester Semester1 { get; set; }
        public virtual Semester Semester2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<semster_student> semster_student { get; set; }
        public virtual study_Group study_Group1 { get; set; }
    }
}
