//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.extra_Course = new HashSet<extra_Course>();
        }
    
        public int id { get; set; }
        public Nullable<int> faculty_member_id { get; set; }
        public string name { get; set; }
        public System.DateTime BOD { get; set; }
        public int major { get; set; }
        public Nullable<int> qualification { get; set; }
        public Nullable<int> degree { get; set; }
        public string email { get; set; }
        public Nullable<int> phone_num { get; set; }
        public string address { get; set; }
        public long national_id { get; set; }
        public int nationality { get; set; }
        public int gender { get; set; }
    
        public virtual degree degree1 { get; set; }
        public virtual major major1 { get; set; }
        public virtual nationality nationality1 { get; set; }
        public virtual qualification qualification1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<extra_Course> extra_Course { get; set; }
    }
}
