using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace CCTT.Pages
{
    public partial class Page__Stadyyear : DevExpress.XtraEditors.XtraUserControl
    {
        // جلب قاعدة البيانات وجدول الاقسام
        DB_CCTTEntities db = new DB_CCTTEntities();
        Year tbYear = new Year();
        int ID;

        public Page__Stadyyear()
        {
            InitializeComponent();
            LoadData();
        }

        public void LoadData()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CCTT.DB_CCTTEntities dbContext = new CCTT.DB_CCTTEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Year.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.Year.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }


        // التاكد من فارغ الدخلات
        private void Add()
        {
            if (txt_stady_year_year.Text == "" || txt_stadyyear_yeartype.SelectedItem == "")
            {
                MessageBox.Show("الحقلول مطلوبة ", "", MessageBoxButtons.OK, MessageBoxIcon.Warning);

            }
            else
            {

                AddData();
                LoadData();
            }
        }
        // دالة اضافة
        private void AddData()
        {
            try
            {

                tbYear.season = txt_stadyyear_yeartype.SelectedItem.ToString();
                
                tbYear.year1 = Convert.ToInt32(txt_stady_year_year.Text);
                tbYear.year_serch = txt_stadyyear_yeartype.SelectedItem.ToString()
                +" "+txt_stady_year_year.Text;

                int idcolg= Convert.ToInt32(txt_stady_year_year.Text);
                idcolg = idcolg % 100;
                if(txt_stadyyear_yeartype.SelectedItem.ToString() == "ربيعي")
                idcolg = (idcolg *10+1)*1000;
                if (txt_stadyyear_yeartype.SelectedItem.ToString() == "خريفي")
                idcolg = (idcolg * 10 + 2) * 1000+1;

                tbYear.idcolge = idcolg;
                db.Entry(tbYear).State = System.Data.Entity.EntityState.Added;
                db.SaveChanges();
                MessageBox.Show("تمت الاضافة بنجاح", "اضافة");
            }
            catch (Exception e)
            {
                MessageBox.Show(e.Message);
            }
        }

        private void btn_Add_Click(object sender, EventArgs e)
        {
            Add();
        }

        private void btn_edt_Click(object sender, EventArgs e)
        {
            try
            {
                ID = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
                if (ID > 0)
                {

                    tbYear = db.Year.Where(x => x.id == ID).FirstOrDefault();
                    tbYear.id = ID;
                    tbYear.season = txt_stadyyear_yeartype.SelectedItem.ToString();
                    if (txt_stady_year_year.Text != "")
                        tbYear.year1 = Convert.ToInt32(txt_stady_year_year.Text);

                  
                    db.Entry(tbYear).State = EntityState.Modified;
                    db.SaveChanges();
                    MessageBox.Show("تم تعديل البيانات بالنجاح", "عملية تعديل", MessageBoxButtons.OK,
                        MessageBoxIcon.Information);
                    LoadData();
                }
                else
                {
                    MessageBox.Show("لا يوجد بيانات لتعديلها");
                }
            }


            catch (Exception exception)
            {
                MessageBox.Show(exception.Message);
            }
        }

     

        private void btn_delete_Click(object sender, EventArgs e)
        {
            var rs = MessageBox.Show("هل انت متأكد من هذا الاجراء , لايمكن استرجاع البيانات", "اجراء حدف", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (rs == DialogResult.Yes)
            {

                try
                {
                    ID = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
                    if (ID > 0)
                    {
                        tbYear = db.Year.Where(x => x.id == ID).FirstOrDefault();

                        db.Entry(tbYear).State = EntityState.Deleted;
                        db.SaveChanges();

                        LoadData();
                    }
                    else
                    {
                        MessageBox.Show("لا يوجد بيانات لحدفها");
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }
        private void gridView1_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            txt_stadyyear_yearcode.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "idcolge").ToString();
            txt_stadyyear_yeartype.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "season").ToString();
            txt_stady_year_year.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "year1").ToString();

        }

        private void txt_stadyyear_yearcode_Enter(object sender, EventArgs e)
        {
            txt_stadyyear_yearcode.BackColor = Color.Yellow;

        }

        private void txt_stadyyear_yearcode_Leave(object sender, EventArgs e)
        {
            txt_stadyyear_yearcode.BackColor = Color.White;

        }

        private void txt_stady_year_year_Enter(object sender, EventArgs e)
        {
            txt_stady_year_year.BackColor = Color.Yellow;

        }

        private void txt_stady_year_year_Leave(object sender, EventArgs e)
        {
            txt_stady_year_year.BackColor = Color.White;

        }

        private void txt_stadyyear_yeartype_Enter(object sender, EventArgs e)
        {
            txt_stadyyear_yeartype.BackColor = Color.Yellow;

        }

        private void txt_stadyyear_yeartype_Leave(object sender, EventArgs e)
        {
            txt_stadyyear_yeartype.BackColor = Color.White;

        }

        private void txt_stadyyear_yearcode_MouseDown(object sender, MouseEventArgs e)
        {
           // eroer

        }

        private void txt_stadyyear_yearcode_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
            else
            {
                return;
            }
        }

        private void txt_stadyyear_yeartype_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsLetter(e.KeyChar) && !char.IsControl(e.KeyChar) && !char.IsWhiteSpace(e.KeyChar))
            {
                e.Handled = true;
            }
        }
    }
}
